- name: Remove Nouveau (blacklist)
  ansible.builtin.copy:
    dest: /etc/modprobe.d/blacklist-nouveau.conf
    content: "{{ lookup('template', 'blacklist-nouveau.conf.j2') }}"
    owner: root
    group: root
    mode: '0644'
  notify: mark_reboot

- name: Update initramfs after blacklisting
  ansible.builtin.command: update-initramfs -u
  changed_when: true
  notify: mark_reboot

- name: Optional | Add graphics-drivers PPA
  ansible.builtin.apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: present
  when: install_graphics_drivers_ppa | bool

- name: Install kernel headers & build tools (for DKMS)
  ansible.builtin.apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"
      - build-essential
      - dkms
    state: present
    update_cache: yes

- name: Install NVIDIA driver (explicit package if set)
  ansible.builtin.apt:
    name: "{{ nvidia_driver_package }}"
    state: present
    update_cache: yes
  when: nvidia_driver_package | length > 0
  notify: mark_reboot

- name: Install NVIDIA driver (auto recommend if not set)
  ansible.builtin.command: ubuntu-drivers install --gpgpu
  args: { creates: /usr/bin/nvidia-smi }
  when: nvidia_driver_package | length == 0
  notify: mark_reboot

- name: Ensure nvidia-smi available
  ansible.builtin.command: nvidia-smi -L
  register: smi
  failed_when: false
  changed_when: false

- name: Flag reboot if driver not yet active
  ansible.builtin.set_fact:
    reboot_required: true
  when: smi.rc != 0
