########################################
        #### NVIDIA DRIVERS ####
########################################
# Source: https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local
- name: Remove Nouveau (blacklist)
  ansible.builtin.copy:
    dest: /etc/modprobe.d/blacklist-nouveau.conf
    content: "{{ lookup('template', 'blacklist-nouveau.conf.j2') }}"
    owner: root
    group: root
    mode: '0644'
  notify: mark_reboot

- name: Update initramfs after blacklisting
  ansible.builtin.command: update-initramfs -u
  changed_when: true
  notify: mark_reboot

- name: Optional | Add graphics-drivers PPA
  ansible.builtin.apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: present
  when: install_graphics_drivers_ppa | bool

- name: Install kernel headers & build tools (for DKMS)
  ansible.builtin.apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"
      - build-essential
      - dkms
    state: present
    update_cache: yes

- name: Download CUDA pin file
  become: yes
  ansible.builtin.get_url:
    url: htps://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
    dest: /etc/apt/preferences.d/cuda-repository-pin-600
    mode: '0644'

- name: Download CUDA local repo installer
  become: yes
  ansible.builtin.get_url:
    url: https://developer.download.nvidia.com/compute/cuda/13.0.1/local_installers/cuda-repo-ubuntu2204-13-0-local_13.0.1-580.82.07-1_amd64.deb
    dest: /tmp/cuda-repo-ubuntu2204-13-0-local_13.0.1-580.82.07-1_amd64.deb
    mode: '0644'

- name: Install CUDA repo package
  become: yes
  ansible.builtin.apt:
    deb: /tmp/cuda-repo-ubuntu2204-13-0-local_13.0.1-580.82.07-1_amd64.deb

- name: Copy CUDA keyring
  become: yes
  ansible.builtin.shell: cp /var/cuda-repo-ubuntu2204-13-0-local/cuda-*-keyring.gpg /usr/share/keyrings/
  changed_when: false

- name: Update apt cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install CUDA toolkit
  become: yes
  ansible.builtin.apt:
    name: cuda-toolkit-13-0
    state: present

- name: Install Nvidia-utils-570-server
  become: yes
  ansible.built.apt:
    name: nvidia-utils-570-server
    state: present
  
- name: Install Nvidia CUDA Drivers
  become: yes
  ansible.built.apt:
    name: nvidia-utils-570-server
    state: present

- name: Flag reboot if driver not yet active
  ansible.builtin.set_fact:
    reboot_required: true
  when: smi.rc != 0


