- name: Install containerd (Ubuntu repo)
  ansible.builtin.apt:
    name: containerd
    state: present
    update_cache: yes
  when: not use_docker_repo_for_containerd

- name: Install Docker repo prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes
  when: use_docker_repo_for_containerd

- name: Add Docker apt key (if using Docker containerd)
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
      | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args: { creates: /etc/apt/keyrings/docker.gpg }
  when: use_docker_repo_for_containerd

- name: Add Docker apt repo (if using Docker containerd)
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    owner: root
    group: root
    mode: '0644'
  when: use_docker_repo_for_containerd

- name: Install containerd.io (Docker-provided)
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: yes
  when: use_docker_repo_for_containerd

- name: Create default config if missing
  ansible.builtin.command: bash -lc "test -f /etc/containerd/config.toml || containerd config default > /etc/containerd/config.toml"
  changed_when: false

- name: Drop tuned containerd config
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify: restart_containerd

# ===== NVIDIA Container Toolkit =====
- name: Add NVIDIA libnvidia-container repo key
  ansible.builtin.shell: |
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
     | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  args: { creates: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg }

- name: Add NVIDIA libnvidia-container repo list
  ansible.builtin.shell: |
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
      | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
      | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  args: { creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list }

- name: apt update after adding NVIDIA CTkit Repo
  ansible.builtin.apt:
    update_cache: yes

- name: Install nvidia-container-toolkit
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    state: present
    update_cache: yes
  notify: restart_containerd

- name: Debug apt policy for nvidia-container-toolkit
  ansible.builtin.shell: apt-cache policy nvidia-container-toolkit | sed -n '1,12p'
  changed_when: false