all:
  children:
    control_plane:
      hosts:
        host-control:
          ansible_host: 192.168.1.110
    workers:
      hosts:
        host-a:
          ansible_host: 192.168.1.210
        host-b:
          ansible_host: 192.168.1.190
    gpu_nodes:
      hosts:
        host-a:
        host-b:
  vars:
    ansible_user: ubuntu-user
    ansible_become: true