---
- name: Install slurm worker packages
  apt:
    name: [slurm-wlm, slurm-wlm-basic-plugins]
    state: present
    update_cache: yes

- name: Ensure slurm dir
  file:
    path: /etc/slurm
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'

- name: Deploy slurm.conf
  template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: slurm
    mode: '0644'
  notify: restart slurmd

- name: Deploy cgroup.conf
  template:
    src: cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: slurm
    mode: '0644'
  notify: restart slurmd

- name: Enable & start slurmd
  systemd:
    name: slurmd
    state: started
    enabled: yes

- name: Handlers
  meta: flush_handlers

- name: restart slurmd
  systemd:
    name: slurmd
    state: restarted
  listen: restart slurmd
