---
- name: Download Puppet release package
  become: yes
  get_url: 
    url: "https://apt.puppetlabs.com/puppet8-release-{{ ansible_lsb.codename }}.deb"
    dest: "/tmp/puppet8-release-{{ ansible_lsb.codename }}.deb"
    mode: '0644'
  register: puppet_release_pkg

- name: Install Puppet release package
  become: yes
  apt:
    deb: "/tmp/puppet8-release-{{ ansible_lsb.codename }}.deb"
  when: puppet_release_pkg is changed

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Install Puppet agent
  apt:
    name: puppet-agent
    state: present
    update_cache: yes

- name: Ensure puppet runs periodically (cron)
  cron:
    name: "puppet agent periodic"
    job: "/opt/puppetlabs/bin/puppet apply /etc/puppetlabs/code/environments/production/manifests/site.pp >/var/log/puppet-apply.log 2>&1"
    minute: "*/15"
    user: root

# Minimal desired-state example: ensure services up
- name: Seed minimal site.pp
  copy:
    dest: /etc/puppetlabs/code/environments/production/manifests/site.pp
    mode: '0644'
    content: |
      package { ['slurm-wlm','slurm-wlm-basic-plugins','munge','verilator','yosys']:
        ensure => present,
      }
      service { 'munge':
        ensure => running, enable => true,
      }
      service { 'slurmd':
        ensure => running, enable => true,
      }
      if $facts['networking']['hostname'] == 'slurm-master' {
        service { 'slurmctld':
          ensure => running, enable => true,
        }
      }
