---
- name: Install Verilator + Yosys + build deps
  apt:
    name:
      - build-essential
      - make
      - git
      - pkg-config
      - bison
      - flex
      - libfl-dev
      - python3
      - python3-pip
      - verilator
      - yosys
    state: present
    update_cache: yes

- name: Verify tools
  shell: |
    set -e
    echo "Verilator: $(verilator --version 2>/dev/null || echo MISSING)"
    echo "Yosys:     $(yosys -V 2>/dev/null || echo MISSING)"
  register: eda_versions
  changed_when: false

- debug:
    var: eda_versions.stdout_lines
