---
- name: Configure Slurm master
  hosts: slurm_master
  become: yes
  vars:
    is_debian: "{{ ansible_os_family == 'Debian' }}"
    is_redhat: "{{ ansible_os_family == 'RedHat' }}"
  tasks:
    - name: Install packages (Debian/Ubuntu)
      when: is_debian
      ansible.builtin.apt:
        name:
          - slurmctld
          - slurmd
          - munge
          - libmunge2
          - libhwloc-dev
        state: present
        update_cache: yes

    - name: Install packages (RHEL)
      when: is_redhat
      ansible.builtin.yum:
        name:
          - slurm
          - slurm-slurmd
          - slurm-slurmctld
          - munge
          - munge-libs
          - hwloc
        state: present

    - name: Generate munge key if not exists
      ansible.builtin.command: /usr/sbin/create-munge-key
      args:
        creates: /etc/munge/munge.key

    - name: Set ownership on munge.key
      ansible.builtin.file:
        path: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: "0400"

    - name: Template slurm.conf
      ansible.builtin.template:
        src: "../../../cluster/slurm/slurm.conf.j2"
        dest: /etc/slurm/slurm.conf
        owner: slurm
        group: slurm
        mode: "0644"

    - name: Template cgroup.conf
      ansible.builtin.template:
        src: "../../../cluster/slurm/cgroup.conf.j2"
        dest: /etc/slurm/cgroup.conf
        owner: slurm
        group: slurm
        mode: "0644"

    - name: Ensure services enabled (munge, slurmctld, slurmd)
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: yes
      loop:
        - munge
        - slurmctld
        - slurmd

    - name: Start services on master
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      loop:
        - munge
        - slurmctld
        - slurmd
