---
- name: Configure Slurm workers
  hosts: slurm_workers
  become: yes
  vars:
    is_debian: "{{ ansible_os_family == 'Debian' }}"
    is_redhat: "{{ ansible_os_family == 'RedHat' }}"
  tasks:
    - name: Install packages (Debian/Ubuntu)
      when: is_debian
      ansible.builtin.apt:
        name:
          - slurmd
          - munge
          - libmunge2
          - hwloc
        state: present
        update_cache: yes

    - name: Install packages (RHEL)
      when: is_redhat
      ansible.builtin.yum:
        name:
          - slurm
          - slurm-slurmd
          - munge
          - munge-libs
          - hwloc
        state: present

    - name: Fetch munge key from master
      delegate_to: slurm-master
      run_once: true
      ansible.builtin.slurp:
        src: /etc/munge/munge.key
      register: munge_key_b64

    - name: Distribute munge key to workers
      ansible.builtin.copy:
        dest: /etc/munge/munge.key
        content: "{{ munge_key_b64['content'] | b64decode }}"
        owner: munge
        group: munge
        mode: "0400"

    - name: Template slurm.conf
      ansible.builtin.template:
        src: "../../cluster/slurm/slurm.conf.j2"
        dest: /etc/slurm/slurm.conf
        owner: slurm
        group: slurm
        mode: "0644"

    - name: Template cgroup.conf
      ansible.builtin.template:
        src: "../../cluster/slurm/cgroup.conf.j2"
        dest: /etc/slurm/cgroup.conf
        owner: slurm
        group: slurm
        mode: "0644"

    - name: Enable services on workers
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: yes
      loop:
        - munge
        - slurmd

    - name: Start services on workers
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      loop:
        - munge
        - slurmd
