# Simple reboot play
#
---
- name: Reboot hosts
  hosts: all
  become: yes
  tasks:
    - name: Reboot the host and wait for it to restart
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami