- name: Phase-1 | Base OS on all nodes
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: base-os
  post_tasks:
    - name: Reboot if base-os requested it
      ansible.builtin.reboot:
        msg: "Rebooting after base-os"
        connect_timeout: 30
        reboot_timeout: 1200
      when: reboot_required | default(false) | bool

- name: Phase-1 | NVIDIA drivers on GPU nodes only
  hosts: gpu_nodes
  gather_facts: yes
  become: yes
  roles:
    - role: nvidia-drivers
  post_tasks:
    - name: Reboot if nvidia-drivers requested it
      ansible.builtin.reboot:
        msg: "Rebooting after nvidia drivers"
        connect_timeout: 30
        reboot_timeout: 1200
      when: reboot_required | default(false) | bool

- name: Phase-1 | containerd everywhere (control + workers)
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: containerd
  post_tasks:
    - name: Restart containerd already handled by role (no reboot)
      ansible.builtin.debug:
        msg: "containerd configured"

- name: Phase-1 | Kubernetes prereqs everywhere
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: kube-prereqs
  post_tasks:
    - name: Final reboot if anything still requested it
      ansible.builtin.reboot:
        msg: "Final reboot after Phase-1"
        connect_timeout: 30
        reboot_timeout: 1200
      when: reboot_required | default(false) | bool
