# Updated Munge playbook to deal with hanging munge key copying when deploying from my laptop
# This allows us to not write the key back to the repo and instead read it from the master in-mem and then push directly to the worker nodes

---
- name: Install munge
  become: yes
  apt:
    name: [munge, libmunge2, libmunge-dev]
    state: present
    update_cache: yes

- name: Ensure munge dirs
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: munge
    group: munge
    mode: "{{ item.mode | default('0700') }}"
  loop:
    - { path: /etc/munge, mode: '0700' }
    - { path: /var/lib/munge, mode: '0700' }
    - { path: /var/log/munge, mode: '0700' }

# Generate a key on the control host just once (the Slurm controller)
- name: Generate munge key on controller if absent
  become: yes
  command: /usr/sbin/mungekey --create
  args: { creates: /etc/munge/munge.key }
  when: inventory_hostname == slurm_control_host

# Read the key contents from the controller into memory
- name: Slurp munge key from controller
  become: yes
  slurp:
    src: /etc/munge/munge.key
  register: munge_key_slurped
  when: inventory_hostname == slurm_control_host
  run_once: true
  delegate_to: "{{ slurm_control_host }}"

# Share the key content to all hosts as a fact
- name: Set munge key fact
  set_fact:
    munge_key_b64: "{{ munge_key_slurped.content }}"
  run_once: true

# Write the key on every host
- name: Distribute munge key to all nodes
  become: yes
  copy:
    content: "{{ munge_key_b64 | b64decode }}"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0400'

- name: Enable & start munge
  become: yes
  systemd:
    name: munge
    state: started
    enabled: yes
