---
- name: Install munge
  apt:
    name: [munge, libmunge2, libmunge-dev]
    state: present
    update_cache: yes

- name: Ensure munge user and dirs
  file:
    path: "{{ item.path }}"
    state: directory
    owner: munge
    group: munge
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - { path: /etc/munge, mode: '0700' }
    - { path: /var/lib/munge, mode: '0700' }
    - { path: /var/log/munge, mode: '0700' }

# Generate key ON MASTER if not already present
- name: Generate munge key (master)
  command: /usr/sbin/mungekey --create
  args: { creates: /etc/munge/munge.key }
  when: inventory_hostname == slurm_control_host

# Fetch it to control machine, then push to others (simple, local fallback)
- name: Fetch munge key from master to controller
  fetch:
    src: /etc/munge/munge.key
    dest: ./munge.key.fetched
    flat: yes
  when: inventory_hostname == slurm_control_host

- name: Copy munge key to role files (controller only)
  delegate_to: localhost
  copy:
    src: ./munge.key.fetched
    dest: roles/munge/files/munge.key
  when: inventory_hostname == slurm_control_host

- name: Distribute munge key to all nodes
  copy:
    src: munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0400'

- name: Enable & start munge
  systemd:
    name: munge
    state: started
    enabled: yes
